library(dplyr)
library(igraph)
globalInfluence <- read.csv("pagerank_data.csv", colClasses = c("factor","factor","integer"))
g <- graph(directed = TRUE, edges = as.character(t(globalInfluence[,1:2])))

# pr <- page_rank(g)
# pr_df <- data.frame(user_id=as.character(names(pr$vector)), pr_value=unname(pr$vector))
# pr_df_ordered <- pr_df%>%arrange(desc(pr_value))
# pr_df_ordered$user_id <-format(pr_df_ordered$user_id, scientific = FALSE) 
# write.csv(pr_df_ordered, quote = FALSE, file = "pagerank_results_factor.csv")

pr_weight <- page_rank(g, weights = globalInfluence$weight)
pr_weight_df <- data.frame(user_id=as.character(names(pr_weight$vector)), pr_value=unname(pr_weight$vector))
pr_weight_df_ordered <- pr_weight_df%>%arrange(desc(pr_value))
write.csv(pr_weight_df_ordered, quote = FALSE, file = "pagerank_weighted_results.csv")
